version: '3.9'

services:
  ecommerce:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./ecommerce:/ecommerce
      - ./data/web:/vol/web

    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=ecommerce
      - DB_USER=postgres
      - DB_PASS=admin
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
